### ISSUE TITLE
Best odl version?

### ISSUE THREAD

**Issue by i3v** [odlgroup/odlworkshop#16]
* `README.md` says "Use the conda variant if possible" (which is 0.5.2 for me on Windows)
* `code/part0_install.ipynb` says `pip install https://github.com/odlgroup/odl/archive/master.zip` (which is 0.6.1dev0)

**Comment by adler-j** [comment]
Good question, for today's exercises the only version that will work is `pip install https://github.com/odlgroup/odl/archive/master.zip`!

**Comment by i3v** [comment]
Now `README.md` is fixed, and everything looks consistent. Thus, AFAIU, this issue should be closed. Thanks for fixing this!
