### ISSUE TITLE
Broken links to notebooks from maxiv-course-oct-17

### ISSUE THREAD

**Issue by i3v** [odlgroup/odlworkshop#27]
The first sentence in "[part1_exercises.ipynb](https://github.com/odlgroup/odlworkshop/blob/2d3144ada11296c5363baba726b1f581a265b087/code/part1_exercises.ipynb)" contains two links ("first" and "two"). It looks like both are broken. Probably, they were related to [these notebooks](https://github.com/kohr-h/maxiv-course-oct-17/tree/fc900291fb5389629fa4263fbae57fc5d07f210e/notebooks), but they are not present in this repo.

**Comment by adler-j** [comment]
Thank you for noting this! I've fixed the links
